### ISSUE TITLE
props spread causes Invalid value for prop `loading` on <img> tag.

### ISSUE THREAD

**Issue by scottbarrow** [Canner/react-loading-image#7]
https://github.com/Canner/react-loading-image/blob/9623d5fb109fea75f270cbcfa0e09ad54e48a131/src/index.js#L96

**Comment by scottbarrow** [comment]
by pasing loading prop this is getting inserted into the img tag by spreading all the props

**Comment by canmihci** [comment]
confirmed.

**Comment by chilijung** [comment]
this is fixed in v0.4.1 please try, thanks!
